services:
  socketplane:
   image: dajeux/socketplane
   volumes:
     - /etc/socketplane/socketplane.toml:/etc/socketplane/socketplane.toml
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/bin/docker
     - /proc:/hostproc
   command: "socketplane"
   network_mode: "host"
   privileged: true
   environment:
     PROCFS: /hostproc
  ovs:
   image: dajeux/docker-ovs:latest
   command: "/usr/bin/supervisord -n"
   network_mode: "host"
   volumes:
     - /etc/openvswitch/
   cap_add:
     - NET_ADMIN
  powerstrip:
   image: dajeux/powerstrip:latest
   network_mode: "host"
   volumes:
     - /etc/socketplane/adapters.yml:/etc/powerstrip/adapters.yml
     - /var/run/docker.sock:/var/run/docker.sock
